apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: reconcile
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: busybox
      command: ["env"]
      envFrom:
        - secretRef:
            name: reconcile-mongo-creds
