apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: reconcile-mongo-creds
  namespace: reconcile
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: reconcile-mongo-creds
  data:
    - secretKey: uri
      remoteRef:
        key: reconcile/mongo-uri
